name:                urlpath
version:             10.0.0
github:              "athanclark/urlpath"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@gmail.com"
copyright:           "Copyright (c) 2023 Athan Clark"

extra-source-files:
- README.md

synopsis:            Painfully simple URL deployment.
category:            Web, Data
description:         Please see the README on Github at <https://github.com/athanclark/urlpath#readme>

ghc-options:
  - -Wall

dependencies:
- base >= 4.11 && < 5
- attoparsec-uri >= 0.0.9
- exceptions
- mmorph
- monad-control
- monad-control-aligned >= 0.0.2
- monad-logger
- mtl
- path >= 0.9
- path-extra >= 0.3.0
- resourcet
- split
- strict
- text
- transformers
- transformers-base
- vector

library:
  source-dirs: src
